// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-a5QcP1N_G6WocySuuVGxG5cKXSxf2R8',
    appId: '1:389123453841:web:ef13462353b808eda5e030',
    messagingSenderId: '389123453841',
    projectId: 'manntravlerapp',
    authDomain: 'manntravlerapp.firebaseapp.com',
    storageBucket: 'manntravlerapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABunPSHdngJs4GKeXN3winEYDSiQsBwvM',
    appId: '1:389123453841:android:89ec990f5fea4f38a5e030',
    messagingSenderId: '389123453841',
    projectId: 'manntravlerapp',
    storageBucket: 'manntravlerapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj1G_nnrYT_xnNnk-o1o8umJAwsdCPwbA',
    appId: '1:389123453841:ios:eefa812760bc7046a5e030',
    messagingSenderId: '389123453841',
    projectId: 'manntravlerapp',
    storageBucket: 'manntravlerapp.firebasestorage.app',
    iosBundleId: 'com.example.mannFleetDriver',
  );
}
